name: Docker

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19'
    - uses: imjasonh/setup-ko@v0.6

    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b #v2.8.1
    - if: github.event_name != 'pull_request'
      env:
        COSIGN_EXPERIMENTAL: true
      run: cosign sign $(ko build ./cmd/golink --bare)

    - if: github.event_name == 'pull_request'
      env:
        KO_DOCKER_REPO: ko.local
      run: ko build ./cmd/golink

